{@@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
{ @@A { @@E {
@@C
}
{@LUse @TblSetup} } }
}
{@LUse @BasicSetup} } }
}
{@LUse @DocumentSetup} } }
}
{@@V @BeginTheoremCounter {}} } }
}
{@@V @TheoremCounterMarker
  \a{"10.2599./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "21 2"
}
{@@V @BeginDefinitionCounter {}} } }
}
{@@V @DefinitionCounterMarker
  \a{"10.2658./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "21 2"
}
{@@V @BeginClaimCounter {}} } }
}
{@@V @ClaimCounterMarker
  \a{"10.2713./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "21 2"
}
{@@V @BeginPropositionCounter {}} } }
}
{@@V @PropositionCounterMarker
  \a{"10.2768./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "21 2"
}
{@@V @BeginLemmaCounter {}} } }
}
{@@V @LemmaCounterMarker
  \a{"10.2823./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "21 2"
}
{@@V @BeginCorollaryCounter {}} } }
}
{@@V @CorollaryCounterMarker
  \a{"10.2878./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@A { @@E {
@@D "21 2"
}
{@@V @BeginExampleCounter {}} } }
}
{@@V @ExampleCounterMarker
  \a{"10.2933./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{{} @Join 0}}}

{@@E {
{ @@B { { @@A { @@E {
@@D "35 3"
}
{Yes @BeginDisplayCounter {}} } }
 }
{@@E {
{ @@A { @@E {
@@D "1623 80"
}
{?? @@V @Do ??} } }
}
{@@V y}} }
}
{@@V @NumDispCounterMarker
  \a{"7.1249./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{{} @Join 0}}}

{@@E {
@@D "21 2"
}
{@@V @FigurePrefixMarker
  \a{"10.3494./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{}}}

{@@E {
@@D "21 2"
}
{@@V @FigureCounterMarker
  \a{"10.3502./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{0}}}

{@@E {
@@D "21 2"
}
{@@V @TablePrefixMarker
  \a{"10.3739./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{}}}

{@@E {
@@D "21 2"
}
{@@V @TableCounterMarker
  \a{"10.3747./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{0}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "21 2"
}
{@@V @PageList
  \a{1}
  \b{Simple}
  \d{Portrait}
  \c{Yes}
1} } }
}
{@@V @SimplePageList
  \a{1}
  \b{Simple}
  \d{Portrait}
  \c{Yes}
  \e{@@V @AtTop}
1} } }
}
{@PageMarker
  \a{"7.1067./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \c{1}
  \b{Arabic @@V @Num 1}}}

{@@E {
@@D "21 2"
}
{@@V @FootNoteCounterMarker
  \a{"10.1381./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
  \b{0}}}

{@@E {
@@D "21 2"
}
{Start @Runner
  \g{"10.796./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.2"}}}

{@@E {
@@D "35 3"
}
{@NumberMarker
  \a{"7.1052./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.2"}
  \b{1}}}

{@@E {
{ @@A { @@E {
{ @@A { @@E {
@@D "21 2"
}
{@LUse @OrdinarySetup} } }
}
{@Text { @LInput }} } }
}
{@@V listitem
  \a{"7.1492./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}
???}}

{@@E {
{ @@A { @@E {
@@D "2509 126"
}
{@@V @SimpleEvenPageList
  \a{1}
  \b{Simple}
2} } }
}
{@PageMarker
  \a{"7.1067./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.2"}
  \c{2}
  \b{Arabic @@V @Num 2}}}

{@@E {
@@D "21 2"
}
{@@V @FootNoteCounterMarker
  \a{"10.1381./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.2"}
  \b{0}}}

{@@E {
{ @@A { @@E {
@@D "21 2"
}
{@@V @SimplePageList
  \a{1}
  \b{Simple}
  \d{Portrait}
3} } }
}
{@PageMarker
  \a{"7.1067./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.3"}
  \c{3}
  \b{Arabic @@V @Num 3}}}

{@@E {
@@D "21 2"
}
{@@V @FootNoteCounterMarker
  \a{"10.1381./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.3"}
  \b{0}}}

{@@E {
@@D "21 2"
}
{NonStart @Runner
  \g{"10.796./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.3"}}}

{@@E {
@@D "21 2"
}
{NonStart @Runner
  \g{"10.796./home/danlo/BrixCode/MoCoAgent/Benchmarker/bench/consumer/typeset/large.lout.1"}}}

